def test_send_message(app):
    app.open_main_page()
    app.open_page("Contact Us")
    app.send_message(name="Alex",
                     second_name="Goryachev",
                     email="alexgor@comcast.net",
                     phone="650-714-8761",
                     subject="Test framework prototype works",
                     message="This message has been generated by framework. "
                             "The test 'send message' is passed'. "
                             "The framework will be available in GIT"
                     )
    # should be some verification here
